server:
  port: 8081


####### resource server configuration properties
spring:
  datasource:
    url: url
    username: username
    password: pw
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/p3t5
          jwk-set-uri: http://localhost:8083/auth/realms/p3t5/protocol/openid-connect/certs