server:
  port: 8081


####### resource server configuration properties
spring:
  neo4j:
    uri: ${NEO4J_URI}
  data:
    neo4j:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/p3t5
          jwk-set-uri: http://localhost:8083/auth/realms/p3t5/protocol/openid-connect/certs