version: '3.4'

services:
  p3t5-db:
    image: mysql:8.0.23
    container_name: p3t5-db
    environment:
     - MYSQL_ROOT_PASSWORD=mysql
     - MYSQL_PASSWORD=mysql
     - MYSQL_USER=mysql
     - MYSQL_DATABASE=p3t5
    ports:
     - 3306:3306
    volumes:
     - ~/apps/mysql:/var/lib/mysql
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
  auth:
    build: auth/
    container_name: p3t5-auth
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
     - 8083:8083
    depends_on:
      p3t5-db:
        condition: service_healthy