version: '3.4'

services:
  p3t5-db:
    image: postgres
    container_name: p3t5-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
     - 5433:5432
    volumes:
     - /db/var/lib/postgresql/data
     - ./db:/docker-entrypoint-initdb.d
  auth:
    build: auth/
    container_name: p3t5-auth
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
     - 8083:8083
    depends_on:
     - "p3t5-db"
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"