package com.fada.project3t5.domain;


import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Match")
@Builder
public class Match {

    //https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/usecases/creating_dynamodb_web_app/src/main/java/com/aws/rest/Work.java

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private Integer playerOne;
    @DynamoDBAttribute
    private Integer playerTwo;
    @DynamoDBAttribute
    private MatchStatus status;
    @DynamoDBAttribute
    private Map<Integer, Move> moves;
}
